language: python
python:
  - 2.7
  - 3.6
  - 3.7-dev

install:
   - pip install -r requirements.txt -r development.txt
   - pip install coveralls

script:
  - ./manage.py test --with-xunit --with-coverage --cover-package=mgsub

after_success:
  - coveralls
