language: python
python:
  - 2.7
  - 3.4

install: "pip install -r requirements.txt -r development.txt"

script:
  - ./manage.py test --with-xunit --xunit-file=shippable/testresults/nosetests.xml --with-coverage --cover-package=mgsub
  - coverage xml -i -o shippable/codecoverage/coverage.xml
